# Generated by Django 4.2.5 on 2023-11-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField()),
                ('release_year', models.CharField(max_length=4)),
                ('label', models.CharField(max_length=100)),
                ('fun_fact', models.TextField()),
            ],
        ),
    ]
