# Generated by Django 4.2.5 on 2023-11-14 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('beatles_site', '0002_track'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='lead_vocals',
            field=models.CharField(default='Lennon and McCartney', max_length=100),
        ),
    ]
